START TRANSACTION;
DROP TABLE IF EXISTS achievements_AbstractMadness;
DROP TABLE IF EXISTS meta_AbstractMadness;
DROP TABLE IF EXISTS trusted_users_AbstractMadness;
DELETE FROM game_ids WHERE gid='AbstractMadness';
INSERT INTO game_ids SET gid='AbstractMadness', cokey='AbstraktiAvain';
CREATE TABLE `achievements_AbstractMadness` LIKE achievements_template;
CREATE TABLE `meta_AbstractMadness` LIKE meta_template;
CREATE TABLE `trusted_users_AbstractMadness` LIKE trusted_users_template;
INSERT INTO `trusted_users_AbstractMadness` SET connection_key='AbstraktiAvain', uid='74798521';
INSERT INTO `meta_AbstractMadness` SET `key`='usedReward', value=0;
INSERT INTO `meta_AbstractMadness` SET `key`='usedSpace', value=0;
INSERT INTO `meta_AbstractMadness` SET `key`='name', value='AbstractMadness\'s game';
COMMIT;