START TRANSACTION;
DROP TABLE IF EXISTS achievements_LKKtest;
DROP TABLE IF EXISTS meta_LKKtest;
DROP TABLE IF EXISTS trusted_users_LKKtest;
DELETE FROM game_ids WHERE gid='LKKtest';
INSERT INTO game_ids SET gid='LKKtest', cokey='LyhytAvain';
CREATE TABLE `achievements_LKKtest` LIKE achievements_template;
CREATE TABLE `meta_LKKtest` LIKE meta_template;
CREATE TABLE `trusted_users_LKKtest` LIKE trusted_users_template;
INSERT INTO `trusted_users_LKKtest` SET connection_key='LyhytAvain', uid='56064140';
INSERT INTO `meta_LKKtest` SET `key`='usedReward', value=0;
INSERT INTO `meta_LKKtest` SET `key`='usedSpace', value=0;
INSERT INTO `meta_LKKtest` SET `key`='name', value='LongKillKreations\'s game';
COMMIT;