START TRANSACTION;
DROP TABLE IF EXISTS achievements_EpicMining2;
DROP TABLE IF EXISTS meta_EpicMining2;
DROP TABLE IF EXISTS trusted_users_EpicMining2;
DELETE FROM game_ids WHERE gid='EpicMining2';
INSERT INTO game_ids SET gid='EpicMining2', cokey='DummyKey';
CREATE TABLE `achievements_EpicMining2` LIKE achievements_template;
CREATE TABLE `meta_EpicMining2` LIKE meta_template;
CREATE TABLE `trusted_users_EpicMining2` LIKE trusted_users_template;
INSERT INTO `trusted_users_EpicMining2` SET connection_key='DummyKey', uid='1187845';
INSERT INTO `meta_EpicMining2` SET `key`='usedReward', value=0;
INSERT INTO `meta_EpicMining2` SET `key`='usedSpace', value=0;
INSERT INTO `meta_EpicMining2` SET `key`='name', value='Epic Mining 2';
COMMIT;