START TRANSACTION;
DROP TABLE IF EXISTS achievements_PowerValkyrie;
DROP TABLE IF EXISTS meta_PowerValkyrie;
DROP TABLE IF EXISTS trusted_users_PowerValkyrie;
DELETE FROM game_ids WHERE gid='PowerValkyrie';
INSERT INTO game_ids SET gid='PowerValkyrie', cokey='PowerfulKey';
CREATE TABLE `achievements_PowerValkyrie` LIKE achievements_template;
CREATE TABLE `meta_PowerValkyrie` LIKE meta_template;
CREATE TABLE `trusted_users_PowerValkyrie` LIKE trusted_users_template;
INSERT INTO `trusted_users_PowerValkyrie` SET connection_key='PowerfulKey', uid='15980724';
INSERT INTO `meta_PowerValkyrie` SET `key`='usedReward', value=0;
INSERT INTO `meta_PowerValkyrie` SET `key`='usedSpace', value=0;
INSERT INTO `meta_PowerValkyrie` SET `key`='name', value='powerhotmail123's Game';
COMMIT;